spring:
  application:
    name: earth-guardian-core
  datasource:
    url: jdbc:postgresql://db.xkxoqqvpdixizlibwrsq.supabase.co:5432/postgres?user=postgres&password=Alpit$Supabase2603
    username: postgres
    password: Alpit$Supabase2603
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
